include:
  - project: 'flownative/operations/build-tools'
    file: '/gitlab-ci/docker.gitlab-ci.yml'
  - project: 'flownative/operations/build-tools'
    file: '/gitlab-ci/docker.release-google.gitlab-ci.yml'
