services:
  - docker:dind

stages:
- build

build-latest:
  stage: build
  image: eu.gcr.io/flownative-beach/gitlab-base-php:7-0
  variables:
    DOCKER_HOST: 'tcp://localhost:2375'
  script:
    - docker login -u _json_key -p "$CI_CONTAINER_REGISTRY_TOKEN" https://eu.gcr.io
    - docker build -t eu.gcr.io/flownative-beach/base:latest .
    - docker push eu.gcr.io/flownative-beach/base:latest

build-tagged:
  stage: build
  script:
    - docker build -t eu.gcr.io/flownative-beach/beach-gateway-ssh:${CI_BUILD_REF_SLUG} .
    - docker push eu.gcr.io/flownative-beach/beach-gateway-ssh:${CI_BUILD_REF_SLUG}
  only:
    - tags
  except:
    - master
