build_image:
  image: docker:git
  services:
  - docker:dind
  script:
    - docker login -e gitlab-runner@flownative-beach.iam.gserviceaccount.com -u _json_key -p "$GOOGLE_SERVICE_ACCOUNT_PASSWORD" https://eu.gcr.io
    - docker build -t eu.gcr.io/flownative-beach/base .
    - docker push eu.gcr.io/flownative-beach/base
  only:
    - master
