services:
  - docker:dind

stages:
- build

variables:
  BUILD_IMAGE_NAME: "eu.gcr.io/flownative-beach/base:$CI_BUILD_REF"
  BUILD_IMAGE_NAME_LATEST: "eu.gcr.io/flownative-beach/base:latest"

build:
  stage: build
  image: eu.gcr.io/flownative-beach/gitlab-base-php:7-0
  variables:
    DOCKER_HOST: 'tcp://localhost:2375'
  script:
    - docker login -u _json_key -p "$CI_CONTAINER_REGISTRY_TOKEN" https://eu.gcr.io
    - docker build -t $BUILD_IMAGE_NAME .
    - docker tag $BUILD_IMAGE_NAME $BUILD_IMAGE_NAME_LATEST
    - docker push $BUILD_IMAGE_NAME
    - docker push $BUILD_IMAGE_NAME_LATEST
