#!/bin/sh
# Compatibility replacement for the install_packages script which was provided
# by bitnami/minideb, the base of this image up to v3.x. Images building on
# this base rely on it for installing their packages.
#
# @TODO
# We also have https://github.com/flownative/bash-library/blob/4914aac4da3e430db6fb7812088749a37b10d4d6/lib/packages.sh#L14
# and both work similarly. Probably remove this and use packages_install everywhere.
set -e
set -u
export DEBIAN_FRONTEND=noninteractive
n=0
max=2
until [ $n -gt $max ]; do
    set +e
    (
      apt-get update -qq &&
      apt-get install -y --no-install-recommends "$@"
    )
    CODE=$?
    set -e
    if [ $CODE -eq 0 ]; then
        break
    fi
    if [ $n -eq $max ]; then
        exit $CODE
    fi
    echo "apt failed, retrying"
    n=$(($n + 1))
done
rm -rf /var/lib/apt/lists /var/cache/apt/archives
