name: Build Docker Image on tag
on:
  push:
    branches-ignore:
      - 'bionic'
      - 'buster'
      - 'bullseye'
    tags:
      - 'v*.*.*'

jobs:
  build:
    uses: ./.github/workflows/docker.build.bookworm.yaml
    secrets: inherit
