name: Build Docker Image on tag
on:
  push:
    branches-ignore:
      - 'bionic'
      - 'buster'
      - 'bullseye'
    tags:
      - 'v*.*.*'

jobs:
  build-bookworm:
    if: startsWith(github.ref_name, 'bookworm') || startsWith(github.ref_name, 'v3.')
    uses: ./.github/workflows/docker.build.bookworm.yaml
    secrets: inherit

  build-trixie-slim:
    if: startsWith(github.ref_name, 'trixie') || startsWith(github.ref_name, 'v4.')
    uses: ./.github/workflows/docker.build.trixie-slim.yaml
    secrets: inherit
